//Auth Types
export const INIT_AUTH = 'INIT_AUTH';

export const SIGN_IN_ERROR = 'SIGN_IN_ERROR';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';

export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS';

//Task Types
export const CREATE_TASK_ERROR = 'CREATE_TASK_ERROR';
export const CREATE_TASK_SUCCESS = 'CREATE_TASK_SUCCESS';

export const REMOVE_TASK_ERROR = 'REMOVE_TASK_ERROR';
export const REMOVE_TASK_SUCCESS = 'REMOVE_TASK_SUCCESS';

export const UNDELETE_TASK_ERROR = 'UNDELETE_TASK_ERROR';

export const UPDATE_TASK_ERROR = 'UPDATE_TASK_ERROR';
export const UPDATE_TASK_SUCCESS = 'UPDATE_TASK_SUCCESS';

export const FILTER_TASKS = 'FILTER_TASKS';
export const LOAD_TASKS_SUCCESS = 'LOAD_TASKS_SUCCESS';
export const UNLOAD_TASKS_SUCCESS = 'UNLOAD_TASKS_SUCCESS';

//Admin Types
export const ADD_COMPETITOR_SUCCESS = 'ADD_COMPETITOR_SUCCES';
export const ADD_COMPETITOR_ERROR = 'ADD_COMPETITOR_ERROR';
export const REMOVE_COMPETITOR_SUCCESS = 'ADD_COMPETITOR_SUCCESS';
export const REMOVE_COMPETITOR_ERROR = 'REMOVE_COMPETITOR_ERROR';

//Notification Types
export const DISMISS_NOTIFICATION = 'DISMISS_NOTIFICATION';
