//Auth Types
export const INIT_AUTH = 'INIT_AUTH';

export const SIGN_IN_ERROR = 'SIGN_IN_ERROR';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';

export const SIGN_IN_EMAIL_SUCCESS = 'SIGN_IN_EMAIL_SUCCESS'
export const SIGN_IN_EMAIL_ERROR = 'SIGN_IN_EMAIL_ERROR'

export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS';

export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_ERROR = 'SIGN_UP_ERROR';

//Task Types
export const CREATE_TASK_ERROR = 'CREATE_TASK_ERROR';
export const CREATE_TASK_SUCCESS = 'CREATE_TASK_SUCCESS';

export const REMOVE_TASK_ERROR = 'REMOVE_TASK_ERROR';
export const REMOVE_TASK_SUCCESS = 'REMOVE_TASK_SUCCESS';

export const UNDELETE_TASK_ERROR = 'UNDELETE_TASK_ERROR';

export const UPDATE_TASK_ERROR = 'UPDATE_TASK_ERROR';
export const UPDATE_TASK_SUCCESS = 'UPDATE_TASK_SUCCESS';

export const FILTER_TASKS = 'FILTER_TASKS';
export const LOAD_TASKS_SUCCESS = 'LOAD_TASKS_SUCCESS';
export const UNLOAD_TASKS_SUCCESS = 'UNLOAD_TASKS_SUCCESS';


//Notification Types
export const DISMISS_NOTIFICATION = 'DISMISS_NOTIFICATION';

//Admin Types
export const CREATE_COMPETITOR_SUCCESS = 'CREATE_COMPETITOR_SUCCESS';
export const CREATE_COMPETITOR_ERROR = 'CREATE_COMPETITOR_ERROR';
export const REMOVE_COMPETITORS_SUCCESS = 'REMOVE_COMPETITORS_SUCCES';
export const REMOVE_COMPETITORS_ERROR = 'REMOVE_COMPETITORS_ERROR';
export const LOAD_COMPETITORS_SUCCESS = 'LOAD_COMPETITORS_SUCCESS'
export const LOAD_COMPETITORS_ERROR = 'LOAD_COMPETITORS_ERROR'
export const FILTER_COMPETITORS = 'FILTER_COMPETITORS'
export const UPDATE_COMPETITOR_SUCCESS = 'UPDATE_COMPETITOR_SUCCESS'
export const UPDATE_COMPETITOR_ERROR = 'UPDATE_COMPETITOR_ERROR'
export const GET_COMPETITION_STATUS_SUCCESS = 'GET_COMPETITION_STATUS_SUCCESS'
export const GET_COMPETITION_STATUS_ERROR = 'GET_COMPETITION_STATUS_ERROR'
export const REMOVE_COMPETITOR_SUCCESS = 'REMOVE_COMPETITOR_SUCCESS'
export const REMOVE_COMPETITOR_ERROR = 'REMOVE_COMPETITOR_ERROR'


//Team Types
export const CREATE_TEAMMATE_SUCCESS = 'CREATE_TEAMMATE_SUCCESS';
export const CREATE_TEAMMATE_ERROR = 'CREATE_TEAMMATE_ERROR';
export const REMOVE_TEAMMATE_SUCCESS = 'REMOVE_TEAMMATE_SUCCES';
export const REMOVE_TEAMMATE_ERROR = 'REMOVE_TEAMMATE_ERROR';
export const LOAD_TEAM_SUCCESS = 'LOAD_TEAM_SUCCESS'
export const LOAD_TEAM_ERROR = 'LOAD_TEAM_ERROR'
export const FILTER_TEAM = 'FILTER_TEAM'
export const UPDATE_TEAMMATE_SUCCESS = 'UPDATE_TEAMMATE_SUCCESS'
export const UPDATE_TEAMMATE_ERROR = 'UPDATE_TEAMMATE_ERROR'
export const PICK_TEAM = 'PICK_TEAM'

//Sign Up 
export const SIGNUP_WITHEMAIL_SUCCESS = 'SIGNUP_WITHEMAIL_SUCCESS'
export const SIGNUP_WITHEMAIL_ERROR = 'SIGNUP_WITHEMAIL_ERROR'

//TeamName Types
export const CREATE_TEAM_NAME_SUCCESS = 'CREATE_TEAM_NAME_SUCCESS'
export const CREATE_TEAM_NAME_ERROR = 'CREATE_TEAM_NAME_ERROR'
export const LOAD_TEAM_NAME_SUCCESS = 'LOAD_TEAM_NAME_SUCCESS'
export const LOAD_TEAM_NAME_ERROR = 'LOAD_TEAM_NAME_ERROR'
export const UPDATE_TEAM_NAME_SUCCESS = 'UPDATE_TEAM_NAME_SUCCESS'
export const UPDATE_TEAM_NAME_ERROR = 'UPDATE_TEAM_NAME_ERROR'


//Competition Action Types
export const CREATE_COMPETITION_SUCCESS = 'CREATE_COMPETITION_SUCCESS';
export const CREATE_COMPETITION_ERROR = 'CREATE_COMPETITION_ERROR';
export const REMOVE_COMPETITION_SUCCESS = 'REMOVE_COMPETITION_SUCCESS';
export const REMOVE_COMPETITION_ERROR = 'REMOVE_COMPETITION_ERROR';
export const LOAD_COMPETITION_SUCCESS = 'LOAD_COMPETITION_SUCCESS'
export const LOAD_COMPETITION_ERROR = 'LOAD_COMPETITION_ERROR'
export const UPDATE_COMPETITION_SUCCESS = 'UPDATE_COMPETITION_SUCCESS'
export const UPDATE_COMPETITION_ERROR = 'UPDATE_COMPETITION_ERROR'

//Profile Types
export const CREATE_PROFILE_SUCCESS = 'CREATE_PROFILE_SUCCESS'
export const CREATE_PROFILE_ERROR = 'CREATE_PROFILE_ERROR'
export const LOAD_PROFILE_SUCCESS = 'LOAD_PROFILE_SUCCESS'
export const LOAD_PROFILE_ERROR = 'LOAD_PROFILE_ERROR'
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS'
export const UPDATE_PROFILE_ERROR = 'UPDATE_PROFILE_ERROR'

//League Types
// export const CREATE_LEAGUE_SUCCESS = 'CREATE_LEAGUE_SUCCESS'
// export const CREATE_LEAGUE_ERROR = 'CREATE_LEAGUE_ERROR'
export const LOAD_LEAGUE_SUCCESS = 'LOAD_LEAGUE_SUCCESS'
export const LOAD_LEAGUE_ERROR = 'LOAD_LEAGUE_ERROR'
// export const UPDATE_LEAGUE_SUCCESS = 'UPDATE_LEAGUE_SUCCESS'
// export const UPDATE_LEAGUE_ERROR = 'UPDATE_LEAGUE_ERROR'

